package fnui.core.annotations

import java.lang.annotation.Retention
import java.lang.annotation.RetentionPolicy

/**
 * The GeneratedCode annotations marks classes generated by (FN)UI.
 */
@Retention(RetentionPolicy.RUNTIME)
@interface GeneratedCode {
}
